feat: add sm and md size attributes
AlaskaAirlines/auro-dialog pull request #7
Opened 2020-09-29 06:23 UTC by ecommerceUXdesign

# Alaska Airlines Pull Request

**Fixes:** #2 

## Summary:

Updates dialog visibility support to include a `sm` and `md` size setting. Default is `lg`. 

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2020-10-01 19:57 UTC, blackfalcon commented
PR is ready for review. Need an assist with tests.

2020-10-02 19:36 UTC, geoffrich requested changes

2020-10-02 19:36 UTC, geoffrich commented on src/auro-dialog.js
> +  aria() {
We should remove aria-hidden altogether when the modal is open. `aria-hidden="false"` [currently behaves inconsistently across browsers.](https://www.w3.org/TR/wai-aria-1.1/#aria-hidden)

2020-10-02 19:36 UTC, geoffrich commented on src/auro-dialog.js
> +  aria() {
Testing with Firefox/NVDA on the demo site, I was unable to read out the contents of an open modal.

2020-10-02 19:36 UTC, geoffrich commented on src/style.scss
> +  &--hidden {
This class doesn't appear to be used anywhere, which is why I can still tab into a closed modal.

2020-10-02 21:47 UTC, blackfalcon approved these changes

2020-10-02 21:49 UTC, merged

2020-10-02 21:51 UTC, ecommerceUXdesign commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@alaskaairux/auro-dialog/v/1.2.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-dialog/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: