Jordanjones243/css imports
AlaskaAirlines/auro-dialog pull request #9
Opened 2024-02-07 22:46 UTC by jordanjones243

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #8 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

* Update references to `unformatted` style links
* Update demo page references

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2024-02-08 01:05 UTC, blackfalcon requested changes
We need to talk about this update. This feature _was_ supported and I am not sure why we are deleting code?

2024-02-08 01:05 UTC, blackfalcon commented on .github/ISSUE_TEMPLATE/publish_component.md
> +    - `index.md`
This whole document can be deleted. The element is already published.

2024-02-08 17:59 UTC, jordanjones243 commented
> We need to talk about this update. This feature _was_ supported and I am not sure why we are deleting code?

The `unformatted` feature is still supported and the examples still work as expected. There was no need for the link to the stylesheet in the example files anymore because we already had `style-unformatted.css` being imported into the component's JS file.

2024-02-13 01:40 UTC, jason-capsule42 approved these changes

2024-02-13 01:40 UTC, merged

2024-02-13 01:42 UTC, jordanjones243 commented
:tada: This PR is included in version 1.0.5 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-dialog/v/1.0.5)
- [GitHub release](https://github.com/AlaskaAirlines/auro-dialog/releases/tag/v1.0.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: